In [16]:
import torch

In [17]:
torch.cuda.is_available()

False

In [18]:
tensor = torch.tensor(list(range(5)))

tensor


tensor([0, 1, 2, 3, 4])

In [19]:
type(tensor)

torch.Tensor

In [20]:
tensor + 2

tensor([2, 3, 4, 5, 6])

In [21]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
torch.zeros_like(tensor)

tensor([0, 0, 0, 0, 0])

In [23]:
tensor_a = torch.randint(1, 10, (2, 3))
tensor_b = torch.randint(1, 10, (3, 2))


In [24]:
tensor_a

tensor([[1, 9, 9],
        [3, 1, 4]])

In [25]:
tensor_b

tensor([[1, 4],
        [2, 9],
        [6, 9]])

In [26]:
torch.matmul(tensor_a, tensor_b)

tensor([[ 73, 166],
        [ 29,  57]])

In [28]:
torch.min(tensor_a)

tensor(1)

In [29]:
torch.max(tensor_b)

tensor(9)

In [32]:
torch.mean(tensor_a, dtype=torch.float32)

tensor(4.5000)

In [33]:
tensor_a.shape

torch.Size([2, 3])

In [35]:
torch.reshape(tensor_a, (3, 2))

tensor([[1, 9],
        [9, 3],
        [1, 4]])