In [1]:
import torch

In [2]:
torch.cuda.is_available()

False

In [3]:
tensor = torch.tensor(list(range(5)))

tensor

tensor([0, 1, 2, 3, 4])

In [4]:
type(tensor)

torch.Tensor

In [5]:
tensor + 2

tensor([2, 3, 4, 5, 6])

In [6]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.zeros_like(tensor)

tensor([0, 0, 0, 0, 0])

In [8]:
tensor_a = torch.randint(1, 10, (2, 3))
tensor_b = torch.randint(1, 10, (3, 2))

In [9]:
tensor_a

tensor([[7, 6, 3],
        [1, 7, 2]])

In [10]:
tensor_b

tensor([[3, 7],
        [7, 9],
        [7, 8]])

In [11]:
torch.matmul(tensor_a, tensor_b)

tensor([[ 84, 127],
        [ 66,  86]])

In [12]:
torch.min(tensor_a)

tensor(1)

In [13]:
torch.max(tensor_b)

tensor(9)

In [14]:
torch.mean(tensor_a, dtype=torch.float32)

tensor(4.3333)

In [15]:
tensor_a.shape

torch.Size([2, 3])

In [16]:
torch.reshape(tensor_a, (3, 2))

tensor([[7, 6],
        [3, 1],
        [7, 2]])

In [17]:
tensor_a_view = tensor_a.view(3, 2)
tensor_a_view[0, 0] = 99

tensor_a_view, tensor_a


(tensor([[99,  6],
         [ 3,  1],
         [ 7,  2]]),
 tensor([[99,  6,  3],
         [ 1,  7,  2]]))

In [28]:
torch.stack([tensor_a_view, tensor_b], dim=1)

tensor([[[99,  6],
         [ 3,  7]],

        [[ 3,  1],
         [ 7,  9]],

        [[ 7,  2],
         [ 7,  8]]])

In [38]:
tensor_c = torch.randint(1, 10, (1, 3, 3))

tensor_c


tensor([[[7, 8, 6],
         [6, 6, 7],
         [5, 8, 7]]])

In [40]:
tensor_c_squeezed = torch.squeeze(tensor_c, dim=0)

tensor_c_squeezed


tensor([[7, 8, 6],
        [6, 6, 7],
        [5, 8, 7]])

In [49]:
tensor_c_squeezed.unsqueeze(dim=1)

tensor([[[7, 8, 6]],

        [[6, 6, 7]],

        [[5, 8, 7]]])

In [53]:
image = torch.rand((224, 224, 3))

image_permute = image.permute(2, 0, 1)

image.shape, image_permute.shape


(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Exercise


In [62]:
random_tensor_a = torch.rand(7, 7)

random_tensor_a


tensor([[0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018],
        [0.9497, 0.6666, 0.9811, 0.0874, 0.0041, 0.1088, 0.1637],
        [0.7025, 0.6790, 0.9155, 0.2418, 0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524, 0.6057],
        [0.3725, 0.7980, 0.8399, 0.1374, 0.2331, 0.9578, 0.3313]])

In [63]:
random_tensor_b = torch.rand(1, 7)

random_tensor_b


tensor([[0.3227, 0.0162, 0.2137, 0.6249, 0.4340, 0.1371, 0.5117]])

In [69]:
random_tensor_a @ random_tensor_b.T

tensor([[1.0466],
        [1.0884],
        [0.9919],
        [0.6820],
        [0.9108],
        [1.0100],
        [0.8004]])

In [72]:
torch.manual_seed(0)

random_tensor_c = torch.rand(7, 7)
random_tensor_d = torch.rand(1, 7)

random_tensor_c @ random_tensor_d.T


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [78]:
torch.manual_seed(7)

random_tensor_e = torch.rand(1, 1, 1, 10)

random_tensor_e, random_tensor_e.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [79]:
random_tensor_e.squeeze(), random_tensor_e.squeeze().shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))